---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Ronald Punt"
subtitle: "Dashboard"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false #'<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
# message:
#  #url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additionnal-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Portal"
    icon: "fas fa-star"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "seo"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/icons/bastillion.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
  - name: "SEO"
    icon: "fa fa-search-minus"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Summersquare"
        logo: "assets/icons/box.png"
        subtitle: "Summersquare Festival"
        tag: "Festival"
        url: "https://www.summersquare.nl"
  - name: "Validators"
    icon: "fa fa-check-circle"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
  - name: "Content"
    icon: "fas fa-book"
    items:
      - name: "Pixabay"
        logo: "assets/tools/sample.png"
        subtitle: "Stunning free images & royalty free stock"
        tag: "Stock"
        url: "https://pixabay.com/nl/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pexels"
        logo: "assets/tools/sample.png"
        subtitle: "Free Stock Photos"
        tag: "Stock"
        url: "https://www.pexels.com"
        target: "_blank" # optional html a tag target attribute
      - name: "CleanPNG"
        logo: "assets/tools/sample.png"
        subtitle: "Find Transparant PNG icons"
        tag: "app"
        url: "https://www.cleanpng.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
  - name: "Dummy Content"
    icon: "fa-solid fa-folder-grid"
    items:
      - name: "HexColorCodes"
        logo: "assets/tools/sample.png"
        subtitle: "Get HTML color codes, Hex color codes, RGB and HSL values with our color picker, color chart and HTML color names. Let's go!"
        tag: "Colors"
        url: "https://hexcolorcodes.org"
        target: "_blank" # optional html a tag target attribute
      - name: "This Person Does Not Exist"
        logo: "assets/tools/sample2.png"
        subtitle: "Random face generator"
        tag: "app"
        url: "https://thispersondoesnotexist.com"
        target: "_blank" # optional html a tag target attribute
      - name: "randomuser.me"
        logo: "assets/tools/sample2.png"
        subtitle: "RANDOM USER GENERATOR"
        tag: "app"
        url: "https://randomuser.me"
        target: "_blank" # optional html a tag target attribute
  - name: "Security Checks"
    icon: "fa-solid fa-camera-cctv"
    items:
      - name: "Website Scanner"
        logo: "assets/icons/paperless.png"
        subtitle: "Discover common web application vulnerabilities and server configuration issues."
        tag: "Website"
        url: "https://pentest-tools.com/website-vulnerability-scanning/website-scanner"
        target: "_blank" # optional html a tag target attribute
      - name: "Microsoft Connectivity Tester"
        logo: "assets/tools/sample.png"
        subtitle: "Test connectivity with MS Products"
        tag: "app"
        url: "https://testconnectivity.microsoft.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "VERIFY HTTP/2 SUPPORT"
        logo: "assets/icons/paperless.png"
        subtitle: "Troubleshoot website, network, and CDN issues for fast resolutions."
        tag: "HTTP"
        url: "https://tools.keycdn.com/http2-test"
        target: "_blank" # optional html a tag target attribute
  - name: "DNS"
    icon: "fa fa-address-book"
    items:
      - name: "Awesome application"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example number 2"
        tag: "app"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "IPlocation.io"
        logo: "assets/tools/sample2.png"
        subtitle: "IP Location Lookup"
        tag: "app"
        url: "https://iplocation.io"
        target: "_blank" # optional html a tag target attribute
  - name: "Resources"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
  - name: "HTML and CSS"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
  - name: "JSON"
    icon: "fa fa-file"
    items:
      - name: "JSON Test"
        logo: "assets/icons/json-icon-24.jpg.png"
        subtitle: "JSONTest.com is a testing platform for services utilizing JavaScript Object Notation (JSON)."
        tag: "JSON"
        url: "http://www.jsontest.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
        target: "_blank" # optional html a tag target attribute
  - name: "Apache / NGinx"
    icon: "fa fa-cloudflare"
    items:
      - name: "THE Ultimate Htaccess"
        logo: "assets/tools/sample2.png"
        subtitle: ".htaccess examples for Apache Webserver"
        tag: "Apache"
        url: "https://www.askapache.com/htaccess/"
        target: "_blank" # optional html a tag target attribute
      - name: "PWA tester online"
        logo: "assets/tools/sample2.png"
        subtitle: "PWA tester online"
        tag: "app"
        url: "https://www.seochecker.it/pwa-tester-online"
        target: "_blank" # optional html a tag target attribute
